### PR TITLE
Remove trailing zeros before parsing JSON

### PR DESCRIPTION
**Pull request by GustavoLCR**
https://github.com/radare/radare2/issues/10613

### CODE REVIEW

**Comment by radare** [comment]
Wtf? Who the hell is appending zeros?

**Comment by radare** [comment]
The error is in r2pipe maybe? Do u have a reproducer for this?

**Comment by GustavoLCR** [comment]
It seems pretty random, but i have a patch for r2pipe: https://github.com/radare/radare2-r2pipe/pull/101

**Comment by radare** [comment]
What about searching for the first occurrence of a null byte and cut there? In theory thats how it should delimited

**Comment by GustavoLCR** [comment]
> What about searching for the first occurrence of a null byte and cut there? In theory thats how it should delimited
> […](#)
> On 22 Jun 2019, at 18:11, GustavoLCR ***@***.***> wrote: It seems pretty random, but i have a patch for r2pipe: [radare/radare2-r2pipe#101](https://github.com/radare/radare2-r2pipe/pull/101) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I don't think it's possible to have a null byte in the middle of the output, so searching from the end should be enough

**Comment by GustavoLCR** [comment]
Also, I don't think this pr will be needed if https://github.com/radare/radare2-r2pipe/pull/101 gets merged

**Comment by radare** [comment]
I think the r2pipe fix is better than patching the testsuite.. but this shouldnt happen at all. I have some more features in mind for the r2pipe api. I added isAvalailable() and updated and released promise, r2r and r2pipe

**Pull request closed without merging**
