### PR TITLE
Improve "unexpected end-of-file" error msg to include line and source

### PR DESCRIPTION
**Pull request by kazarmy**
**Detailed description**

This pr improves the "unexpected end-of-file" error message to include line and source.

**Test plan**

The following at the end of `tools/r2`:

```
NAME=radare2 -i -Q with missing script
FILE=-
CMDS=<<EOF
# Should not hang
!radare2 -i script/missing.r2 -NQ -
EOF
EXPECT=<<EOF
EOF
EXPECT_ERR=<<EOF
Script 'script/missing.r2' not found.
RUN
```

should result in something like the following:

unexpected_eof

**Closing issues**

See description.

### CODE REVIEW

**Comment by radare** [comment]
btw can you use .endsWith() instead of slicing with substrings and comparing the end o f string with  === ?

**Comment by kazarmy** [comment]
??? may i know which lines of code you're referring to?

**Comment by radare** [comment]
index.js

 889   t.name = line.split('BROKEN')[0].trim();
 890   if (tmp[tmp.length - 1] === 'BROKEN') {
 891     tmp = tmp.slice(0, tmp.length - 1);
 892     t.cmd = tmp.join(' ');

**Comment by kazarmy** [comment]
ok #24

**Pull request merged**
